# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.CharField(max_length=200),
        ),
    ]
