# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170105_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic_url',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cart_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
