# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170105_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
